packages/launcher/__tests__/__snapshots__/router.test.tsx.snap
packages/launcher/__tests__/router.test.tsx

test: add router title and lazy test case

test: add router title and lazy test case

---

packages/launcher/hooks/use-router.ts

fix: add useRouter declare

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/todo-plan.md

feat: Update issue templates

---

packages/launcher/package.json
packages/launcher/rollup.config.js
packages/launcher/tsconfig.json

refactor: refactor build dir and chore package config

refactor: refactor build dir and chore package config

---

README.md

docs: add badge for readme

---

packages/docs/docusaurus.config.js
packages/docs/package.json

docs: add doc package script deploy env & modify config

docs: add doc package script deploy env & modify config

---

packages/launcher/package.json

modify launcher npm package name: @aktiv/launcher

chore: modify launcher npm package name: @aktiv/launcher

---

packages/docs/package.json
packages/launcher/__tests__/utils/istype.test.ts
packages/launcher/package-lock.json
packages/launcher/package.json
packages/launcher/src/utils/isType.ts

feat: add kind-of for judge value's type and refactor test suits
**other type verify，kind-of lib had help us done.**

feat: add kind-of for judge value's type and refactor test suits

---

.eslintrc.js
packages/launcher/CHANGELOG.md
packages/launcher/README.md
packages/launcher/__tests__/hooks/useRouter.test.tsx
packages/launcher/__tests__/router.test.tsx
packages/launcher/package-lock.json
packages/launcher/package.json
packages/launcher/src/app.tsx
packages/launcher/src/hooks/use-router.ts
packages/launcher/src/router/render-routers.tsx
packages/launcher/src/router/wrapper-route.tsx
packages/launcher/src/utils/globalEnv.ts
packages/launcher/src/wrapperInit.tsx

add basename and add basename to useRouter and redirect

feat: add basename and add basename to useRouter and redirect

---

.eslintrc.js
packages/launcher/__tests__/store.test.tsx

refactor: refactor store test

---

.travis.yml
package.json

chore: modifyg .travis and root script

chore: modifyg .travis and root script

---

packages/launcher/README.md
packages/launcher/src/app.tsx

BREAKING CHANGE
feat: add rootNode options

feat: add rootNode options

---

packages/launcher/__tests__/hooks/useQuery.test.tsx

Add useQuery test

---

packages/launcher/README.md
packages/launcher/__tests__/store.test.tsx
packages/launcher/src/app.tsx
packages/launcher/src/store/index.ts

support add custom reduxMiddleware

feat: support add custom reduxMiddleware

---

packages/launcher/package.json

fix(launcher): @types/kind-of 为dev依赖

fix(launcher): @types/kind-of 为dev依赖

---

packages/cli/package.json
pnpm-lock.yaml

fix(cli): 增加terser-webpack-plugin依赖

---

package.json
packages/cli/bin/ak-dev.js
packages/cli/config/index.js

style: change typo

---

packages/cli/utils/prepareUrl.js

fix: fix port behind :

---

packages/cli/bin/ak-init.js

fix(cli): 修复终止安装仍会输出正确的错误

---

packages/cli/ak-template/.eslintrc.js
packages/cli/utils/createCaCertificate.js

style: fix file prefix for jsx

style: fix file prefix for jsx

---

pnpm-lock.yaml

fix: 修复升级pnpm是导致的隐形依赖升级

---

commitlint.config.js

chore(root): 增加commitlint scope enum, scope不能为空

chore(root): 增加commitlint scope enum, scope不能为空

---

.swcrc
.travis.yml
package.json
packages/cli/ak-webpack-config/index.js
packages/cli/jest.config.js
packages/launcher/jest.config.js
pnpm-lock.yaml

chore(root): use swc/jest

---

packages/launcher/src/utils/isType.ts

perf(launcher): use type predicates

---

.travis.yml

chore(root): 修复travis ci

---

packages/cli/ak-webpack-config/index.js
packages/cli/ak-webpack-config/lib/webpackConfig.js

feat(cli): add externalsType receive

---

packages/cli/ak-webpack-config/index.js
packages/cli/ak-webpack-config/lib/plugins/defaultPlugins.js
packages/cli/bin/ak-dev.js

add ReactRefreshPluginOptions receive

feat(cli): add ReactRefreshPluginOptions receive

---

packages/cli/ak-template/.stylelintrc.json
packages/cli/ak-template/package.json

fix(cli): fix stylelint and prettier conflict

fix(cli): fix stylelint and prettier conflict
